Reports/ccsuzzh/[WeeklyReport]2023.11.13~2023.11.26.md
[WeeklyReport]ccsuzzh 2023.11.13~2023.11.26
=> [WeeklyReport] ccsuzzh 2023.11.13~2023.11.26

Reports/Hhankyangg/[WeeklyReport]2023.11.13~2023.11.26.md
[WeeklyReport]Hhankyangg 2023.11.13~2023.11.26
=> [WeeklyReport] Hhankyangg 2023.11.13~2023.11.26

Reports/wyyang23/[WeeklyReport]2023.11.13~2023.11.26.md
=> [WeeklyReport] wyyang23 add 2023.11.13~2023.11.26

Reports/zade23/[WeeklyReport]2023.11.13_2023.11.26.md
张安铎
1. 基础方向：框架API易用性提升
2. 大模型方向：Custom Diffusion 训练支持；Checkpoint Merger
- 完成热身打卡一和二
- 完成已挂名的Docthon英文文档修复任务
- 完成Custom Diffusion 训练支持
=> [WeeklyReport]YangWulve 2023.11.13~2023.11.26 

Reports/sanbuphy/[WeeklyReport]2023.11.27~2023.12.10.md
[WeeklyReport] sanbuphy 2023.11.27~2023.12.10
=> [WeeklyReport] sanbuphy 2023.11.27~2023.12.10

Reports/wyyang23/[WeeklyReport]2023.11.26~2023.12.10.md
=> [WeeklyReport] wyyang23 2023.11.26~2023.12.10

Reports/shiofjsaio/[WeeklyReport]2023.11.27~2023.12.8.md
谢关平
PaddleMIX ppdiffusers中models模块升级自编码器相关代码
1. **任务 X**
正在熟悉PaddleMIX ppdiffusers中models模块升级自编码器相关代码
2. **问题疑惑与解答**
无
1. 完成PaddleMIX ppdiffusers中models模块升级自编码器相关代码升级任务
=> [WeeklyReport] shiofjsaio 2023.11.17~2023.12.10.

Reports/GreatV/[WeeklyReport]2023.12.11~2023.12.24.md
- [WeeklyReport] GreatV 2023.12.11~2023.12.24
=> [WeeklyReport] GreatV 2023.12.11~2023.12.24

community/docs_group/Meeting/【第 3 期例会】会议纪要.md
有哪些需要补充的吗qaq~
@sunzhongkai588 @SigureMo
=> 第三期Docs女团出道日常例会会议纪要

community/docs_group/Meeting/【第 5 期例会】会议纪要.md
【第 5 期例会】会议纪要
可能大概就这些了，好像这次会议讲的挺少的QAQ
@sunzhongkai588 @ooooo-create
=> 【第 5 期例会】会议纪要

Reports/zade23/[WeeklyReport] zade23 2023.12.26~2024.1.19.md
=> [WeeklyReport] zade23 2023.12.26~2024.1.19

Reports/Hhankyangg/[WeeklyReport]2023.12.25~2024.1.19.md
[WeeklyReport] Hhankyangg 2023.12.25~2024.1.19
=> [WeeklyReport] Hhankyangg 2023.12.25~2024.1.19

Reports/sanbuphy/[WeeklyReport]2023.12.26~2024.1.19.md
=> [WeeklyReport] sanbuphy 2023.12.26~2024.1.19

community/docs_group/Meeting/【第 6 期例会】会议纪要.md
大佬们看下
@SigureMo @sunzhongkai588 @ooooo-create
=> 【第 6 期例会】会议纪要

Reports/season 2/LittleNoob2333/[WeeklyReport]2024.03.25~2024.04.07.md
姓名
王赟龙(LittleNoob2333)
本双周工作
完成热身打卡任务
报错日志优化 已提交PR
未来双周计划
尝试认领并完成其他类型任务
详细周报链接：
#154
=> LittleNoob2333 add 2024.03.25~2024.04.7 WeeklyReport

Reports/season 2/hu-qi/[WeeklyReport]2024.03.25~2024.04.07.md
hu-qi
1. 完成热身打卡
2. 修复石墨文档(文档团)部分问题
1. 继续跟进 [`markdown table` 渲染问题](https://github.com/PaddlePaddle/docs/pull/6568)。
2. 完成[补充 Overview 文档相关 API 描述](https://github.com/PaddlePaddle/docs/issues/6427)部分任务。
3. 尝试参与 [PFCC 社区博客新功能开发](https://github.com/PFCCLab/blog/issues)。
=> [WeeklyReport] hu-qi 2024.03.20~2024.04.03

Reports/season 2/LouisCanbe/[WeeklyReport] 2024.03.25~2024.04.07.md
=> [WeeklyReport] LouisCanBe 2024.03.25~2024.04.07.md

community/docs_group/Meeting/【第 11 期例会】会议纪要.md
=> 【第 11 期例会】会议纪要

Reports/season 2/Eddie-Wang/[WeeklyReport]2024.04.08~2024.04.21.md
王晋恒 (Eddie-Wang)
- 【PIR OpTest Fix No.22】 fix test_elementwise_sub_op
1. **PR 合入**
- PaddlePaddle/docs Fix Fleet docs bug 
2. **Paddle 代码阅读**
- codegen
- prim
- pir
- phi
2. **完成快乐开源任务**
1. 继续合入更多pr
=> [WeeklyReport] Eddie-Wang 2024.04.08~2024.04.21

Meeting/README.md
=> add online course video link

Reports/season 2/Eddie-Wang/[WeeklyReport]2024.04.22~2024.05.06.md
王晋恒 (Eddie-Wang)
- 【PIR OpTest Fix No.22】 fix test_elementwise_sub_op
1. **Paddle 代码阅读**
- vjp
- composite
1. 继续合入更多pr
=> [WeeklyReport] Eddie-Wang 2024.04.22~2024.05.06

Reports/season 2/LouisCanbe/[WeeklyReport] 2024.04.22~2024.05.06.md
双周报LouisCanBe 2024.04.22~2024.05.06
=> [WeeklyReport] LouisCanBe 2024.04.22~2024.05.06

Reports/season 2/smallpoxscattered/[WeeklyReports]2024.04.22~2024.05.06.md
[[WeeklyReports] 2024.04.22~2024.05.06 周报收集](https://github.com/PFCCLab/Starter/issues/194)#194
=> [WeeklyReports] smallpoxscattered 2024.04.22~2024.05.05

Meeting/README.md
=> add online course

Reports/season 3/inaomIIsFarell/[WeeklyReport]2024.7.15~2024.7.26.md
陆楚龙（inaomIIsFarell）
PIR单测推全
1. **任务1: 热身打卡任务**
使用AI studio完成paddle本地编译
2. **任务 2：PIR单测推全**
针对PIR Unittest No.398, No.399的问题提交PR（未合入，仍在修改中）https://github.com/PaddlePaddle/Paddle/pull/66299
3. **问题疑惑与解答**
- ctest -R xxx 与 python xxx 之间的区别
答：前者使用本地编译的paddle下进行测试，后者使用python环境中的paddle进行测试
1. 完成PIR单测推全修复任务中剩余的任务
2. 认领并开始**Type Hints**任务 https://github.com/PaddlePaddle/Paddle/issues/65008
=> [WeeklyReport]inaomIIsFarell 2024.7.15~2024.7.26

Reports/season 2/lwkhahaha/[WeeklyReport]2024.07.17~2024.07.26.md
梁微琨
1. 提交3PIR的PR，合入1PR
2. 提交1文档打卡PR
1. 完成报错信息优化任务
2. 完成公开API标注类型提示信息
https://github.com/PFCCLab/Starter/pull/258
=> [WeeklyReport] lwkhahaha 2023.07.17~2023.07.26

community/docs_group/Meeting/【第 16 期例会】会议纪要.md
会议时间：2024/7/30 17:00-18:00 （GMT+08:00）中国标准时间-北京
=> 【第 16 期例会】会议纪要

Reports/season 3/Lans1ot/[WeeklyReport]2024.07.28~2024.08.09.md
=> [WeeklyReport] Lans1ot 2024.07.27~2024.08.09

Reports/season 3/Betelgeu/[WeeklyReport]2024.07.27~2024.08.09.md
=> [WeeklyReport] Betelgeu 2024.07.27~2024.08.09

Reports/season 3/lwkhahaha/[WeeklyReports] 2024.07.27~2024.08.09.md
梁微琨
合入2个CINN任务
合入4个报错信息优化任务
合入1个文档打卡任务
继续完成CINN任务
继续完成报错信息优化任务
继续完成TypeHint任务
https://github.com/PFCCLab/Starter/pull/326
=> [WeeklyReport] lwkhahaha 2024.07.27~2024.08.09

Reports/season 3/successfulbarrier/[WeeklyReport]2024.07.29~2024.08.11.md
=> [WeeklyReport] successfulbarrier 2024.07.29~2024.08.11

Reports/season 3/yeteye/[WeeklyReports] 2024.07.27~2024.08.09.md
曹浩(yeteye)
- 图例31、41、60
1. **热身打卡任务**
- 使用AI Studio完成推理演绎
2. **文档团任务**
- 修改flip函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6816
- 添加split函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6815
- 添加vstack函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6817
3. **问题疑惑与解答**
- 问题 a：ai studio 推理演绎的训练慢
答：不需要训练完，只需展示可以训练即可进入推理
1. 进行文档bug修改
2. 进行文档图例添加
https://github.com/PFCCLab/Starter/pull/309
=> [WeeklyReport]yeteye WeeklyReport2024.07.29 ~ 2024.0809.md

Reports/season 3/Jeff114514/[WeeklyReport]2024.08.10~2024.08.23.md
=> [WeeklyReport]Jeff114514 WeeklyReport2024.08.10 ~ 2024.08.23.md

Reports/season 3/yeteye/[WeeklyReports] 2024.08.10~2024.08.23.md
曹浩(yeteye)
- 添加图例31
1. **文档团任务**
- 修改flip函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6816
- 添加split函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6815
- 添加dstack函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6842
- 添加unstack函数的功能示例
- https://github.com/PaddlePaddle/docs/pull/6840
1. 进行文档bug修改
2. 进行文档图例添加
=> [WeeklyReport] yeteye 2024.8.10~2024.8.23

Reports/season 4/XavierZXY/[WeeklyReports]2024.11.18~2024.11.29.md
Others
Others
XavierZXY [WeeklyReports] 2024.11.18~2024.11.29
=> [WeeklyReports] 2024.11.18~2024.11.29

Reports/season 4/MrXnneHang/2024.11.18~2024.11.29.md
docs
Report from 11.10~11.29 exactly.
=> [WeeklyReport] MrXnneHang 2024.11.18~2024.11.29

Reports/season 4/xz-alex/[WeeklyReport]2024.11.18~2024.11.30.md
xz-alex weekly report: 2024.11.18-2024.11.30
=> [WeeklyReport] xz-alex 2024.11.18~2024.11.30

Reports/season 4/ZHOU05030/[WeeklyReport]2024.11.15.dd1~2024.11.29.md
=> ZHOU05030 add weeklyreport

Reports/season 3/Turingg/[WeeklyReport]2024.08.24~2024.09.08.md
姓名
许芸欣
PIR模式下单测问题修复与适配
1. https://github.com/PaddlePaddle/Paddle/issues/63740 660
1.完成 https://github.com/PaddlePaddle/Paddle/issues/63740 660
2.认领 https://github.com/PaddlePaddle/Paddle/issues/63740 659
https://github.com/PFCCLab/Starter/pull/393
=> [WeeklyReport]Turingg WeeklyReport2024.08.24 ~ 2024.09.06

Reports/season 4/XavierZXY/[WeeklyReports]2024.11.18~2024.11.29.md, Reports/season 4/XavierZXY/[WeeklyReports]2024.11.29~2024.12.13.md
- [PaddleMix快乐开源-5-LLaVA-Video-7B-Qwen2推理](https://github.com/PaddlePaddle/PaddleMIX/issues/787)
1. **LLaVA-Video-7B-Qwen2推理对齐**
- 开始进行`LLaVA-Video-7B-Qwen2`的推理对齐工作，目前已经完成了部分对齐工作
1. 基本完成paddlemix中`LLaVA-Video-7B-Qwen2`推理对齐
=> [WeeklyReports] XavierZXY 2024.11.29~2024.12.13

Reports/season 4/XavierZXY/[WeeklyReports]2024.12.13~2024.12.27.md
- [PaddleMix快乐开源-5-LLaVA-Video-7B-Qwen2推理](https://github.com/PaddlePaddle/PaddleMIX/issues/787)
1. **LLaVA-Video-7B-Qwen2推理对齐**
- 进行`LLaVA-Video-7B-Qwen2`的推理对齐工作，目前已经完成了部分对齐工作
2. **问题疑惑与解答**
- 遇到了模型显存占用过大的问题，正在解决中
1. 基本完成paddlemix中`LLaVA-Video-7B-Qwen2`推理对齐
=> [WeeklyReports] XavierZXY 2024.12.13~2024.12.27

Reports/season 5/Echo-Nie/[WeeklyReports] 2025.04.07~2025.04.18.md
https://github.com/PFCCLab/Starter/issues/585
=> [WeeklyReport] Echo-Nie 2025.04.07~2025.04.18
